============================================================================
     To: All                           Number: 119      Refer: 0098    
   From: Nathan Bright             Conference: FidoQBasic   (139)
   Date: 08-19-95 14:21              BBS Name: Exec-PC
Subject: Game over screen...           BBS ID: EXECPC
----------------------------------------------------------------------------

Here's an AWESOME game over screen that you could use in a game...
-------------  BEGIN   GAMEOVER.BAS   -----   CUT HERE! ------------
CLS
SCREEN 12
CIRCLE (180, 70), 50, 2, .785, 6, 2
CIRCLE STEP(0, 0), 60, 2, .785, 6.2, 2
LINE STEP(30, 5)-STEP(-40, 0), 2
LINE STEP(0, 0)-STEP(0, 10), 2
LINE STEP(0, 0)-STEP(34, 0), 2
LINE STEP(-1, -56)-STEP(-5, 6), 2
PAINT STEP(0, -2), 2
LINE STEP(70, 0)-STEP(-30, 96), 1
LINE STEP(0, 0)-STEP(10, 0), 1
LINE STEP(0, 0)-STEP(12, -37), 1
LINE STEP(0, 0)-STEP(15, 0), 1
LINE STEP(0, 0)-STEP(12, 37), 1
LINE STEP(0, 0)-STEP(10, 0), 1
LINE STEP(0, 0)-STEP(-30, -96), 1
LINE STEP(0, 30)-STEP(-6, 19), 1
LINE STEP(0, 0)-STEP(13, 0), 1
LINE STEP(0, 0)-STEP(-6, -19), 1
PAINT STEP(0, -5), 1
LINE STEP(80, -25)-STEP(-30, 96), 3
LINE STEP(0, 0)-STEP(10, 0), 3
LINE STEP(0, 0)-STEP(12, -37), 3
LINE STEP(0, 0)-STEP(4.8, -15), 3
LINE STEP(0, 0)-STEP(4.8, 15), 3
LINE STEP(0, 0)-STEP(12, 37), 3
LINE STEP(0, 0)-STEP(12, -37), 3
LINE STEP(0, 0)-STEP(4.8, -15), 3
LINE STEP(0, 0)-STEP(4.8, 15), 3
LINE STEP(0, 0)-STEP(12, 37), 3
LINE STEP(0, 0)-STEP(10, 0), 3
LINE STEP(0, 0)-STEP(-30, -96), 3
LINE STEP(0, 0)-STEP(-1.5, 0), 3
LINE STEP(0, 0)-STEP(-12, 37), 3
LINE STEP(0, 0)-STEP(-12, -37), 3
LINE STEP(0, 0)-STEP(-1.5, 0), 3
PAINT STEP(27, 1), 3
LINE STEP(55, -1)-STEP(-5, 96), 5
LINE STEP(0, 0)-STEP(50, -2), 5
LINE STEP(0, 0)-STEP(-1, -15), 5
LINE STEP(0, 0)-STEP(-30, -2), 5
LINE STEP(0, 0)-STEP(2, -23), 5
LINE STEP(0, 0)-STEP(15, -1), 5
LINE STEP(0, 0)-STEP(-1, -10), 5
LINE STEP(0, 0)-STEP(-15, 1), 5
LINE STEP(0, 0)-STEP(-1, -30), 5
LINE STEP(0, 0)-STEP(25, -1), 5
LINE STEP(0, 0)-STEP(-1, -15), 5
LINE STEP(0, 0)-STEP(-38, 2), 5
PAINT STEP(1, 1), 5
CIRCLE (200, 210), 60, 4, , , .75
CIRCLE STEP(0, 0), 50, 4, , , .75
PAINT STEP(55, 0), 4
LINE STEP(10, -55)-STEP(30, 96), 4
LINE STEP(0, 0)-STEP(30, -96), 4
LINE STEP(0, 0)-STEP(-10, 0), 4
LINE STEP(0, 0)-STEP(-20, 62.5), 4
LINE STEP(0, 0)-STEP(-20, -62.5), 4
LINE STEP(0, 0)-STEP(-10, 0), 4
PAINT STEP(3, 1), 4
LINE STEP(75, -1)-STEP(-0, 96), 4
LINE STEP(0, 0)-STEP(50, -0), 4
LINE STEP(0, 0)-STEP(-0, -13), 4
LINE STEP(0, 0)-STEP(-37, -0), 4
LINE STEP(0, 0)-STEP(0, -26), 4
LINE STEP(0, 0)-STEP(15, -0), 4
LINE STEP(0, 0)-STEP(-0, -10), 4
LINE STEP(0, 0)-STEP(-15, 0), 4
LINE STEP(0, 0)-STEP(-0, -35), 4
LINE STEP(0, 0)-STEP(32, -0), 4
LINE STEP(0, 0)-STEP(-0, -12), 4
LINE STEP(0, 0)-STEP(-45, 0), 4
PAINT STEP(1, 1), 4
LINE STEP(82, 95)-STEP(-12, -96), 4, BF
CIRCLE STEP(18, 35), 35, 4, 4.53, 1.75
CIRCLE STEP(0, 0), 25, 4, 4.5, 1.8
PAINT STEP(0, -26), 4
LINE STEP(20, 56)-STEP(20, 32), 4
LINE STEP(0, 0)-STEP(-10, 0), 4
LINE STEP(0, 0)-STEP(-20, -32), 4
PAINT STEP(6, 4), 4
-----------------  END   GAMEOVER.BAS  ------  END CUT HERE! -----------
Enjoy d00d's!
--- Renegade v10-05 Exp.
 * Origin: Briery Branch BBS | 540-828-4608 | Bridgewater, VA (1:2629/2)
                                                                                
                    
